name: Package

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: yarn
            - run: yarn build
            - name: Set env
              run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
            - name: Upload
              uses: svenstaro/upload-release-action@v1-release
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/BMWStatus-${{ env.RELEASE_VERSION }}.dmg
                  asset_name: BMWStatus-${{ env.RELEASE_VERSION }}.dmg
                  tag: ${{ github.ref }}
                  overwrite: true
